### ISSUE TITLE
Too large of mbox

### ISSUE THREAD

**Issue by JAMESWATTS1995** [jarrodparkes/mbox-to-csv#14]
Hi Jarrod

Hope all is well. I'm wondering if my mbox file (has thousands of emails) is too large

Do you think this would be an create mistakes an my the start code process; i do note, every time i run the script it slows my computer down to near frozen

**Comment by JAMESWATTS1995** [comment]
3.1 gigabyte

**Comment by jarrodparkes** [comment]
@JAMESWATTS1995 I've personally not tested anything that large, nor have I really done anything to consider performance. There may very well be things which could be done in order to improve the script performance. I've also been investigating tools like https://github.com/mailgun/flanker (by team behind MailGun) which may provide feature and performance boosts.

**Comment by JAMESWATTS1995** [comment]
Thank you. Will look into this. Have a good day
